---
title: "rspecでエラーテストが失敗する"
draft: false
tags: ["rails","ruby","rspec"]
private: false
slug: "5b43c92f-d394-416c-9877-0ecc11e77366"
date: "2020-02-17T13:41:57+09:00"
lastmod: "2020-02-17T14:28:23+09:00"
keywords: ["rails","ruby","rspec","ベジプロ","プログ","プログラム"]
# headless: true
---

# 解決
`export { subject }` に変更

```rb
context "test" do
  subject { raise RuntimeError }
  it { expect { subject }.to raise_error(RuntimeError) }
end
```

# 事象
`Failure/Error: raise RuntimeError` が発生する。

```rb
context "test" do
  subject { raise RuntimeError }
  it { is_expected.to raise_error(RuntimeError) }
end
```

> [RSpec の is_expected で raise_error を検知したかった - Secret Garden(Instrumental)](http://secret-garden.hatenablog.com/entry/2016/09/01/000000)

## RSpec/ImplicitSubject エラー
[Class: RuboCop::Cop::RSpec::ImplicitSubject — Documentation for rubocop-rspec (1.38.1)](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitSubject) により、
`is_expected` の使用は禁止されていたので下記の記法はできなくなった。

`subject` には、 procを渡す必要がある。

```rb
  subject { -> { raise RuntimeError } }
```

```!
この場合、 is_expected.to eq "return value" の比較はできなくなるので、比較系とエラー系でsubjectを分ける必要がある。
```
